# Generated by Django 5.0.4 on 2024-05-22 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('user_profile', '0007_alter_playlist_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='commenter',
                    to=settings.AUTH_USER_MODEL)
                 ),
                ('likes', models.ManyToManyField(
                    blank=True,
                    related_name='playlist_comments',
                    to=settings.AUTH_USER_MODEL)
                 ),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistPost',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(
                    blank=True, 
                    related_name='playlist_likes', 
                    to=settings.AUTH_USER_MODEL)
                 ),
                ('playlist', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='playlists',
                    to='user_profile.playlist')
                 ),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='core.playlistpost'),
        ),
    ]
