# Generated by Django 5.0.4 on 2024-05-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_playlistpost_delete_album_comment_post'),
        ('user_profile', '0007_alter_playlist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistpost',
            name='playlist',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='playlist_post',
                to='user_profile.playlist'),
        ),
    ]
