# Generated by Django 5.0.4 on 2024-05-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_playlistpost_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='playlist_post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
