# Generated by Django 5.0.4 on 2024-06-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_likes_comment_likes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistpost',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
