# Generated by Django 5.0.4 on 2024-06-17 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
