# Generated by Django 5.0.4 on 2024-05-10 12:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_playlist_playlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default='placeholder',
                max_length=255,
                verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='performance_year',
            field=models.IntegerField(
                blank=True, null=True,
                verbose_name='Year of Performance'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='song_audio',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                verbose_name='audios'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='song_tabs',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                verbose_name='docs'),
        ),
    ]
