# Generated by Django 5.0.4 on 2024-05-14 00:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_playlist_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
