# Generated by Django 5.0.4 on 2024-05-19 12:23
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_playlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='song_comments',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about_myself',
            field=models.TextField(blank=True, verbose_name='about myself'),
        ),
    ]
