# Generated by Django 5.0.4 on 2024-05-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_playlist_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistitem',
            name='song_video',
        ),
    ]
