# Generated by Django 5.0.4 on 2024-06-11 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_alter_playlist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(
                blank=True,
                validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='song_comments',
            field=models.TextField(
                blank=True,
                validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about_myself',
            field=models.TextField(
                blank=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='about myself'),
        ),
    ]
