# Generated by Django 5.0.4 on 2024-06-13 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_alter_playlist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='song_comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(800)]),
        ),
    ]
