# Generated by Django 5.0.4 on 2024-06-13 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_alter_playlist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_myself',
            field=models.TextField(
                blank=True,
                validators=[django.core.validators.MaxLengthValidator(1000)],
                verbose_name='about myself'),
        ),
    ]
