# Generated by Django 5.0.4 on 2024-06-14 19:55

import cloudinary.models
import user_profile.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_alter_userprofile_about_myself'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='song_audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[user_profile.validators.validate_file_size, user_profile.validators.validate_audio_file_type], verbose_name='audios'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='song_tabs',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[user_profile.validators.validate_file_size, user_profile.validators.validate_tabs_file_type], verbose_name='docs'),
        ),
    ]
