# Generated by Django 5.0.4 on 2024-06-14 19:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_alter_userprofile_about_myself'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='song_audio',
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name='audios'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='song_tabs',
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name='docs'),
        ),
    ]
