# Generated by Django 5.0.4 on 2024-06-01 12:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorSection',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('title', models.CharField(max_length=200)),
                ('profile_image', cloudinary.models.CloudinaryField(
                    default='placeholder',
                    max_length=255,
                    verbose_name='image')
                 ),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
            ],
        ),
    ]
