# Generated by Django 5.0.4 on 2024-06-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorsection',
            name='reference_url',
            field=models.URLField(blank=True),
        ),
    ]
